### ISSUE TITLE
Finalize Design Doc

### ISSUE THREAD

**Issue by samuelgriffey0** [captaincobbs/CS_2450_Application#9]
finalize the design doc

**Comment by sc700** [comment]
Finalized

**Comment by sc700** [comment]
[software-requirement-document_complete.pdf](https://github.com/user-attachments/files/17070317/software-requirement-document_complete.pdf)

**Comment by samuelgriffey0** [comment]
Needs updating with current copy of use cases and test case spread sheet

**Comment by sc700** [comment]
[software-req_doc_revised.pdf](https://github.com/user-attachments/files/17081879/software-req_doc_revised.pdf)

Here's the design document with the revised test and use cases.
